### PR TITLE
Task frontend

### PR DESCRIPTION
**Pull request by Terry-Hawk**
Added the html files for the Edit Task, Create New Task, Task Details, and Group Projects Dashboard

### CODE REVIEW

**Comment by Terry-Hawk** [comment]
Wanted to test getting the files in with early files to make sure I did it correctly.

**Comment by fujohn** [comment]
Hey Terry, I see the files changed and its the creation of the HTML files with no content yet. Will push this for now as the setup, but let me know if there is supposed to be more items to this

**Review by fujohn — APPROVED** [review]
All Pages set up

**Comment by Terry-Hawk** [comment]
No more items have been pushed yet, I had some issues before with my gut
hub integration so I wanted to test it. It seems that it worked and
everything is good now. Thanks

**Pull request merged**
